version: 2
jobs:
  build:
    machine:
    steps:
      - checkout

      - run:
          name: Install Bundler
          command: bundle install

      - run:
          name: Build and Test
          command: bundle exec fastlane build_and_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - device_farm:
          requires:
            - build
